version: '3.3'

services:
  postgres:
    build: backend/postgres-dev/
    ports:
    - 5432:5432
    volumes:
    - ./backend/db_data/:/var/lib/postgresql/db_data
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB_LIST: $POSTGRES_DATABASE_LIST
  
  adminer:
    image: adminer
    restart: always
    ports:
    - 8090:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  personality_analysis:
    build: backend/personality_analysis
    depends_on:
    - postgres
    command: sh ./docker-entrypoint.sh
    restart: always
    ports:
    - 5050:5050
    environment: 
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: $PERSONALITY_DB